Implement null model
DataBiosphere/analysis_pipeline_WDL pull request #29
Opened 2021-06-30 00:24 UTC by aofarrel

Includes checker workflow.

Known quirks:
* Does not include the phenotype metadata inheritance function, as it appears it would not work off SB and does not appear to make any difference to the output phenotype file. This is documented in the code itself and where appropriate in this repo.
* The output null model file tends to vary from what you'd get on SB. It seems its in the realm of a rounding error but we have only looked at one such example in detail.

2021-07-06 17:03 UTC, aofarrel commented
Merged PR in which the checker model is now powered by R.

2021-07-12 20:44 UTC, juklucas requested changes
Looks great. At this point, I'd make changes similar to what I suggested for n_pcs for:
- family
- inverse_normal
- rescale_variance
- n_pcs
- resid_covars

At that point Avani and I can restart the review process.

2021-07-13 16:28 UTC, aofarrel commented on null-model/null-model-wf.wdl
> +				f.write('n_pcs ~{n_pcs}\n')
But it wouldn't match what Stephanie does. Stephanie does not check for a default value, she instead checks for whether or not something is defined. It's a minor distinction but it's actually behind a couple of bugs in the CWL so I think it's a distinction we need to keep making.

2021-07-13 18:05 UTC, aofarrel commented on null-model/null-model-wf.wdl
> +	Boolean isdefined_npcs = defined(n_pcs)
https://github.com/DataBiosphere/analysis_pipeline_WDL/pull/29#discussion_r668926479

2021-07-13 23:34 UTC, aofarrel commented on null-model/null-model-wf.wdl
> +		Int? n_pcs
https://github.com/DataBiosphere/analysis_pipeline_WDL/pull/29#discussion_r668926479

2021-07-13 23:35 UTC, aofarrel commented on null-model/README.md
> +## More Information
Thank you!

2021-07-13 23:37 UTC, aofarrel commented on null-model/checker/are_outputs_kinda_equal.R
> +stopifnot(isFALSE(identical(test, truth)))
This line is very useful in debugging situations where there is more than one output file, which in previous versions of this code was very error-prone. I've ironed out all the bugs I could find, meaning it is no longer required, but I'm hesitant to remove it considering I want to use this code for more complicated checker workflows later down the line.

2021-07-19 18:31 UTC, aofarrel commented on _test-data-and-truths_/null_model/README.md
> +These files were taken straight from the original Python pipeline's repo, with the exception of the two Null_model_mixed* files which came from the GENESIS Null Model sample workspace, based upon Rev
The files have been unchanged for quite some time, so I don't think pointing to a commit is worth it. But I'm still open to the idea. Take a look at the new readmes and see what you think.

2021-07-19 20:36 UTC, aofarrel commented on null-model/null-model-wf.wdl
> +# Most pipelines so far use a .config file to point requiste inputs to the Rscript.
Ugh!

2021-07-20 00:20 UTC, closed without merging

2021-07-20 16:48 UTC, juklucas commented on null-model/null-model-wf.wdl
> +				f.write('n_pcs ~{n_pcs}\n')
You are quite right, she does a check for whether or not the user has defined n_pcs. Considering that we assign a default value in the inputs section, this check doesn't really mean anything for us.

2021-07-20 18:47 UTC, aofarrel commented on null-model/null-model-wf.wdl
> +				f.write('n_pcs ~{n_pcs}\n')
I'm confused. We don't assign a default value in the inputs section.

2021-07-20 19:42 UTC, aofarrel commented on null-model/null-model-wf.wdl
> +				f.write('n_pcs ~{n_pcs}\n')
Solved via Slack -- sbg:toolDefaultValue doesn't seem to write anything, it just seems to show a UI element.

2021-07-20 23:50 UTC, aofarrel commented on null-model/null-model-wf.wdl
> +	#
Accidentally put this in, then reverted it -- let me know if anything else gets lost.